### PR TITLE
Running pipeline locally

### PR DESCRIPTION
**Pull request by VincentLa**
This PR does two main things:

1. Cleans up some of the parser code so that instead of absolute paths pointing to raw data files, use relative paths. This will make it easier to run on any machine (instead of just my own)
2. Added a lot more documentation on how to run the pipeline locally, and how to set up your local DB with production data

### CODE REVIEW

**Comment by VincentLa** [comment]
@avdonovan Added a lot more documentation here on getting set up locally and running the `pipeline_runner.py`

**Comment by VincentLa** [comment]
Ok this is ready to go now I think.

**Review by avdonovan — CHANGES_REQUESTED** [review]
Thanks for updating the documentation so quickly!  This has been quite helpful as I'm learning how the pipeline is set up.

One more thing I'd like to see: which of the files in pipeline_runner.py should be commented out?  It looks like as it currently stands in the repo, the files in queries/ will regenerate tables in stg_analytics and trg_analytics from data_ingest.  But if data_ingest hasn't been populated, does one need to uncomment some of the other files in pipeline_runner.py?  Is it safe just to leave all files uncommented?

I also added a couple small commits to this branch; please review.

**Comment by makfan64** [comment]
Looks good to me. Any comments from @avdonovan ? EDIT: oops, when I refreshed, there they were!

**Review by makfan64 — APPROVED** [review]

**Review by makfan64 — APPROVED** [review]

**Comment by VincentLa14** [comment]
@avdonovan I reviewed your changes those look good to me. In addition, I added in a `run_parse` argument to the command line interface for the `pipeline_runner`. I think this addresses your concerns about ad-hoc commenting out of files and such.

**Comment by makfan64** [comment]
I like the change to pipeline_runner.

**Review by avdonovan — APPROVED** [review]
Looks good!

**Comment by VincentLa14** [comment]
Thanks all!

**Pull request merged**
